version: '3'

services:
  redis:
    build: ./redis
    ports:
      - 6379:6379

  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  aiopocketurls:
    build: ./aiopocketurls
    expose:
      - '5000'
    depends_on:
      - redis
      - postgres

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - aiopocketurls
