apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: aiopocketurls
    tier: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: aiopocketurls
    tier: backend
