apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: aiopocketurls
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: aiopocketurls
        tier: backend
    spec:
      containers:
      - name: aiopocketurls
        image: rbielenia/aiop:latest
        resources:
          requests:
            cpu: 1
            memory: 128Mi
        ports:
        - containerPort: 5000
