apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      containers:
      - name: master
        image: rbielenia/postgres:latest
        resources:
          requests:
            cpu: 1
            memory: 128Mi
        ports:
        - containerPort: 5432
        envFrom:
            - configMapRef:
                name: postgres-config
        volumeMounts:
            - mountPath: /var/lib/postgresql/
              name: postgredb                
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-disk                
